name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      videoId:
        description: 'ID of the video'
        required: true
        default: ''

jobs:
  build:
    runs-on: node:lts-bullseye-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print input values
        run: |
          echo "ID: ${{ github.event.inputs.videoId }}"

      - name: Fetch and store video metadata in data.json
        run: |
          echo "ID: ${{ github.event.inputs.videoId }}"
          node ./tools/storeVideoMetadata.js ${{ github.event.inputs.videoId }}

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b add-${{ github.event.inputs.videoId }}

      - name: Commit changes
        run: |
          git add data.json
          git commit -m 'Update data.json with new entry'
          git push --set-upstream origin update-data-json

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-data-json
          title: 'Update data.json with new entry'
          body: "This PR updates data.json with a new entry for ${{ github.event.inputs.videoId }}"
          labels: "automated-pr"
